#!/usr/bin/env python3
from __future__ import annotations
import glob, hashlib, json, pathlib

MECH=pathlib.Path("epsilon_challenge/EPSILON_V7_COMPRESSION_MECHANICS.tsv")
TASK=pathlib.Path("epsilon_challenge/MAX_LOSSLESS_TASK.md")

rows=[]
for line in MECH.read_text(encoding="utf-8").splitlines():
    if not line: continue
    p=line.split("\t")
    if len(p)!=3: raise SystemExit("malformed mechanics projection")
    rows.append(tuple(p))
if len(rows)!=67: raise SystemExit(f"expected 67 mechanics relations, got {len(rows)}")
relations=set(rows)
required={
 ("lossless compression candidate","requires","exact inverse verification"),
 ("lossless compression candidate","requires","complete child size accounting"),
 ("compression decision","should prefer","smallest verified exact candidate"),
 ("transform chain","requires","inverse transforms applied in reverse order"),
 ("lossless plateau","requires","testing materially applicable transform classes and orderings"),
 ("failed compression candidate","should preserve","negative evidence and failure reason"),
}
missing=required-relations
if missing: raise SystemExit("missing mechanics: "+repr(sorted(missing)))

variants=[]
families={}
for p in sorted(glob.glob("candidate_max_*.json")):
    d=json.loads(pathlib.Path(p).read_text())
    fam=d.get("family","unknown")
    vv=d.get("variants",[])
    variants.extend(vv)
    exact=[x for x in vv if x.get("exact") and isinstance(x.get("complete_bytes"),int)]
    families[fam]=min(exact,key=lambda x:x["complete_bytes"]) if exact else None

passing=[x for x in variants if x.get("exact") and isinstance(x.get("complete_bytes"),int)]
if not passing: raise SystemExit("no exact candidate")
passing.sort(key=lambda x:(x["complete_bytes"],x.get("carrier_bytes") or 10**30,x["name"]))
best=passing[0]

report={
 "subject":"Epsilon V7 maximum lossless compression task",
 "objective":"smallest tested complete lossless representation of canonical enwik9; no preset size target",
 "source_bytes":1_000_000_000,
 "source_sha256":"159b85351e5f76e60cbe32e04c677847a9ecba3adc79addab6f4c6c7aa3744bc",
 "mechanics_rows":len(rows),
 "mechanics_sha256":hashlib.sha256(MECH.read_bytes()).hexdigest(),
 "task_sha256":hashlib.sha256(TASK.read_bytes()).hexdigest(),
 "tested_variants":len(variants),
 "exact_variants":len(passing),
 "family_incumbents":families,
 "selected_incumbent":best,
 "top_exact":passing[:20],
 "failed_or_inexact":[x for x in variants if not x.get("exact")],
 "stopping_interpretation":"TESTED_PLATEAU only if every scheduled adaptive family search completed and no later tested neighbor improved the incumbent; never a global optimum claim",
 "global_optimum_claim":False,
 "tool_authorship_boundary":"Epsilon's preserved compression relations govern exactness, acceptance/rejection, composition, and smallest-candidate selection. The reversible primitive source code and orchestration are external workshop affordances unless independently generated by Epsilon."
}
pathlib.Path("EPSILON_V7_MAX_LOSSLESS_RESULT.json").write_text(json.dumps(report,indent=2))
print(json.dumps(report,indent=2))
